version: '3'
services:
  mlflow:
    build:
      context: .
      dockerfile: ./docker/mlflow/Dockerfile
      target: develop
    volumes:
      - ./:/src
      - ./docker/mlflow/tmp:/src/venv
    tty: true
    ports: 
      - "5000:5000"
    restart: always

  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
      target: develop
    volumes:
      - ./project:/src/project
      - ./docker/jupyter/tmp:/project/venv
    tty: true
    ports:
      - "8000:8000"
    restart: always
    depends_on: 
      - mlflow
